import io
from typing import Dict, Any, List
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors

def _create_styles() -> Dict[str, ParagraphStyle]:
    """Helper to initialize and customize ReportLab paragraph styles."""
    styles = getSampleStyleSheet()
    
    # Custom colors
    primary_color = colors.HexColor("#2563eb")  # Professional blue
    text_color = colors.HexColor("#1f2937")     # Dark charcoal
    
    # Add unique custom styles or modify existing
    title_style = ParagraphStyle(
        'DocTitle',
        parent=styles['Heading1'],
        fontName='Helvetica-Bold',
        fontSize=24,
        leading=28,
        textColor=primary_color,
        spaceAfter=15
    )
    
    subtitle_style = ParagraphStyle(
        'DocSubtitle',
        parent=styles['Normal'],
        fontName='Helvetica-Oblique',
        fontSize=12,
        leading=16,
        textColor=colors.HexColor("#4b5563"),
        spaceAfter=25
    )
    
    h2_style = ParagraphStyle(
        'SectionHeading',
        parent=styles['Heading2'],
        fontName='Helvetica-Bold',
        fontSize=16,
        leading=20,
        textColor=colors.HexColor("#1e3a8a"),
        spaceBefore=15,
        spaceAfter=10,
        keepWithNext=True
    )
    
    body_style = ParagraphStyle(
        'DocBody',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=10,
        leading=14,
        textColor=text_color,
        spaceAfter=10
    )
    
    bold_body = ParagraphStyle(
        'DocBodyBold',
        parent=body_style,
        fontName='Helvetica-Bold'
    )
    
    table_cell = ParagraphStyle(
        'TableCell',
        parent=body_style,
        fontSize=9,
        leading=12,
        spaceAfter=0
    )
    
    table_cell_bold = ParagraphStyle(
        'TableCellBold',
        parent=table_cell,
        fontName='Helvetica-Bold'
    )

    return {
        "title": title_style,
        "subtitle": subtitle_style,
        "h2": h2_style,
        "body": body_style,
        "bold_body": bold_body,
        "table_cell": table_cell,
        "table_cell_bold": table_cell_bold
    }

def generate_team_pdf(team_name: str, stats_summary: Dict[str, Any], streak_info: Dict[str, Any], best_season_info: Dict[str, Any], recent_matches: List[Dict[str, Any]]) -> bytes:
    """
    Generates a PDF report summarizing a team's historical performance.
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter, rightMargin=40, leftMargin=40, topMargin=40, bottomMargin=40)
    story = []
    
    sty = _create_styles()
    
    # 1. Header
    story.append(Paragraph(f"IPL Team Report: {team_name}", sty["title"]))
    story.append(Paragraph("Generated by IPL Data Analytics Hub", sty["subtitle"]))
    story.append(Spacer(1, 10))
    
    # 2. Section: Overview
    story.append(Paragraph("Performance Summary", sty["h2"]))
    
    # Grid of stats
    overview_data = [
        [
            Paragraph("Metric", sty["table_cell_bold"]), 
            Paragraph("Value", sty["table_cell_bold"]),
            Paragraph("Metric", sty["table_cell_bold"]), 
            Paragraph("Value", sty["table_cell_bold"])
        ],
        [
            Paragraph("Matches Played", sty["table_cell"]),
            Paragraph(str(stats_summary.get("Matches Played", 0)), sty["table_cell"]),
            Paragraph("Win Percentage", sty["table_cell"]),
            Paragraph(f"{stats_summary.get('Win Percentage (%)', 0)}%", sty["table_cell"])
        ],
        [
            Paragraph("Matches Won", sty["table_cell"]),
            Paragraph(str(stats_summary.get("Matches Won", 0)), sty["table_cell"]),
            Paragraph("Highest Win Streak", sty["table_cell"]),
            Paragraph(str(streak_info.get("Highest Winning Streak", 0)), sty["table_cell"])
        ],
        [
            Paragraph("Matches Lost", sty["table_cell"]),
            Paragraph(str(stats_summary.get("Matches Lost", 0)), sty["table_cell"]),
            Paragraph("Current Form Streak", sty["table_cell"]),
            Paragraph(str(streak_info.get("Current Streak", 0)), sty["table_cell"])
        ],
        [
            Paragraph("Best Season", sty["table_cell"]),
            Paragraph(f"{best_season_info.get('Best Season', 'N/A')} ({best_season_info.get('Win Rate (%)', 0):.1f}% wins)", sty["table_cell"]),
            Paragraph("Home Ground Record", sty["table_cell"]),
            Paragraph(f"{stats_summary.get('Home Wins', 0)} Wins / {stats_summary.get('Home Played', 0)} Played", sty["table_cell"])
        ]
    ]
    
    t_overview = Table(overview_data, colWidths=[130, 130, 130, 130])
    t_overview.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.HexColor("#f3f4f6")),
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor("#e5e7eb")),
        ('PADDING', (0,0), (-1,-1), 6),
        ('ALIGN', (0,0), (-1,-1), 'LEFT'),
        ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
    ]))
    story.append(t_overview)
    story.append(Spacer(1, 20))
    
    # 3. Recent Matches Table
    story.append(Paragraph("Recent Match History (Last 10 Contests)", sty["h2"]))
    
    match_rows = [
        [
            Paragraph("Date", sty["table_cell_bold"]),
            Paragraph("Opponent", sty["table_cell_bold"]),
            Paragraph("Venue / City", sty["table_cell_bold"]),
            Paragraph("Toss Decision", sty["table_cell_bold"]),
            Paragraph("Winner", sty["table_cell_bold"]),
            Paragraph("Result Details", sty["table_cell_bold"])
        ]
    ]
    
    for m in recent_matches:
        match_rows.append([
            Paragraph(str(m.get("date", "N/A")), sty["table_cell"]),
            Paragraph(str(m.get("opponent", "N/A")), sty["table_cell"]),
            Paragraph(f"{m.get('venue', 'N/A')} ({m.get('city', 'N/A')})", sty["table_cell"]),
            Paragraph(f"{m.get('toss_winner', 'N/A')} ({m.get('toss_decision', 'N/A')})", sty["table_cell"]),
            Paragraph(str(m.get("winner", "N/A")), sty["table_cell"]),
            Paragraph(str(m.get("result", "N/A")), sty["table_cell"])
        ])
        
    t_matches = Table(match_rows, colWidths=[65, 95, 130, 85, 75, 70])
    t_matches.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.HexColor("#1e3a8a")),
        ('TEXTCOLOR', (0,0), (-1,0), colors.white),
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor("#e5e7eb")),
        ('PADDING', (0,0), (-1,-1), 5),
        ('VALIGN', (0,0), (-1,-1), 'TOP'),
    ]))
    # Quick fix for text color in table header
    for i in range(len(match_rows[0])):
        match_rows[0][i].style.textColor = colors.white
        
    story.append(t_matches)
    
    # Build Document
    doc.build(story)
    buffer.seek(0)
    return buffer.getvalue()

def generate_player_pdf(player_name: str, batting_profile: Dict[str, Any], bowling_profile: Dict[str, Any]) -> bytes:
    """
    Generates a PDF player profile.
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter, rightMargin=40, leftMargin=40, topMargin=40, bottomMargin=40)
    story = []
    
    sty = _create_styles()
    
    story.append(Paragraph(f"IPL Player Profile: {player_name}", sty["title"]))
    story.append(Paragraph("Generated by IPL Data Analytics Hub", sty["subtitle"]))
    story.append(Spacer(1, 10))
    
    # Batting Section
    if batting_profile:
        story.append(Paragraph("Batting Career Statistics", sty["h2"]))
        bat_data = [
            [Paragraph("Innings", sty["table_cell_bold"]), Paragraph(str(batting_profile.get("Innings", 0)), sty["table_cell"])],
            [Paragraph("Runs Scored", sty["table_cell_bold"]), Paragraph(str(batting_profile.get("Runs", 0)), sty["table_cell"])],
            [Paragraph("Balls Faced", sty["table_cell_bold"]), Paragraph(str(batting_profile.get("Balls Faced", 0)), sty["table_cell"])],
            [Paragraph("Batting Average", sty["table_cell_bold"]), Paragraph(str(batting_profile.get("Average", "N/A")), sty["table_cell"])],
            [Paragraph("Strike Rate", sty["table_cell_bold"]), Paragraph(f"{batting_profile.get('Strike Rate', 0):.2f}", sty["table_cell"])],
            [Paragraph("Highest Score", sty["table_cell_bold"]), Paragraph(str(batting_profile.get("Highest Score", 0)), sty["table_cell"])],
            [Paragraph("50s / 100s", sty["table_cell_bold"]), Paragraph(f"{batting_profile.get('50s', 0)} / {batting_profile.get('100s', 0)}", sty["table_cell"])],
            [Paragraph("Fours / Sixes", sty["table_cell_bold"]), Paragraph(f"{batting_profile.get('Fours', 0)} / {batting_profile.get('Sixes', 0)}", sty["table_cell"])],
        ]
        t_bat = Table(bat_data, colWidths=[200, 320])
        t_bat.setStyle(TableStyle([
            ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor("#e5e7eb")),
            ('PADDING', (0,0), (-1,-1), 6),
            ('BACKGROUND', (0,0), (0,-1), colors.HexColor("#f9fafb")),
        ]))
        story.append(t_bat)
        story.append(Spacer(1, 20))
        
    # Bowling Section
    if bowling_profile:
        story.append(Paragraph("Bowling Career Statistics", sty["h2"]))
        bowl_data = [
            [Paragraph("Innings Bowled", sty["table_cell_bold"]), Paragraph(str(bowling_profile.get("Innings", 0)), sty["table_cell"])],
            [Paragraph("Wickets Taken", sty["table_cell_bold"]), Paragraph(str(bowling_profile.get("Wickets", 0)), sty["table_cell"])],
            [Paragraph("Overs Delivered", sty["table_cell_bold"]), Paragraph(str(bowling_profile.get("Overs", 0.0)), sty["table_cell"])],
            [Paragraph("Economy Rate", sty["table_cell_bold"]), Paragraph(f"{bowling_profile.get('Economy', 0.0):.2f}", sty["table_cell"])],
            [Paragraph("Bowling Average", sty["table_cell_bold"]), Paragraph(str(bowling_profile.get("Average", "N/A")), sty["table_cell"])],
            [Paragraph("Bowling Strike Rate", sty["table_cell_bold"]), Paragraph(str(bowling_profile.get("Strike Rate", "N/A")), sty["table_cell"])],
            [Paragraph("Best Bowling Figures", sty["table_cell_bold"]), Paragraph(str(bowling_profile.get("Best Figures", "N/A")), sty["table_cell"])],
            [Paragraph("3W / 5W Hauls", sty["table_cell_bold"]), Paragraph(f"{bowling_profile.get('3W Hauls', 0)} / {bowling_profile.get('5W Hauls', 0)}", sty["table_cell"])],
        ]
        t_bowl = Table(bowl_data, colWidths=[200, 320])
        t_bowl.setStyle(TableStyle([
            ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor("#e5e7eb")),
            ('PADDING', (0,0), (-1,-1), 6),
            ('BACKGROUND', (0,0), (0,-1), colors.HexColor("#f9fafb")),
        ]))
        story.append(t_bowl)
        
    doc.build(story)
    buffer.seek(0)
    return buffer.getvalue()

def generate_predictor_pdf(prediction_data: Dict[str, Any]) -> bytes:
    """
    Generates a PDF log of a win prediction scenario.
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter, rightMargin=40, leftMargin=40, topMargin=40, bottomMargin=40)
    story = []
    
    sty = _create_styles()
    
    story.append(Paragraph("IPL Match Outcome Simulation", sty["title"]))
    story.append(Paragraph("Generated by ML Win Predictor Engine", sty["subtitle"]))
    story.append(Spacer(1, 10))
    
    story.append(Paragraph("Match Setup & State", sty["h2"]))
    
    state_data = [
        [Paragraph("Parameter", sty["table_cell_bold"]), Paragraph("Value", sty["table_cell_bold"])],
        [Paragraph("Batting Team (Chasing)", sty["table_cell"]), Paragraph(prediction_data["batting_team"], sty["table_cell"])],
        [Paragraph("Bowling Team (Defending)", sty["table_cell"]), Paragraph(prediction_data["bowling_team"], sty["table_cell"])],
        [Paragraph("Venue City", sty["table_cell"]), Paragraph(prediction_data["city"], sty["table_cell"])],
        [Paragraph("Target Score", sty["table_cell"]), Paragraph(str(prediction_data["target_runs"]), sty["table_cell"])],
        [Paragraph("Current Score", sty["table_cell"]), Paragraph(str(prediction_data["current_score"]), sty["table_cell"])],
        [Paragraph("Wickets Fallen", sty["table_cell"]), Paragraph(str(prediction_data["wickets_fallen"]), sty["table_cell"])],
        [Paragraph("Overs Bowled", sty["table_cell"]), Paragraph(f"{prediction_data['overs_input']:.1f}", sty["table_cell"])],
    ]
    t_state = Table(state_data, colWidths=[200, 320])
    t_state.setStyle(TableStyle([
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor("#e5e7eb")),
        ('PADDING', (0,0), (-1,-1), 6),
        ('BACKGROUND', (0,0), (0,-1), colors.HexColor("#f9fafb")),
    ]))
    story.append(t_state)
    story.append(Spacer(1, 20))
    
    story.append(Paragraph("Prediction Outcome", sty["h2"]))
    
    pred_data = [
        [Paragraph("ML Pipeline Model", sty["table_cell_bold"]), Paragraph(prediction_data["model_name"].replace("_", " ").title(), sty["table_cell"])],
        [Paragraph("Batting Team Win Probability", sty["table_cell_bold"]), Paragraph(f"{prediction_data['batting_win_prob']:.2f}%", sty["table_cell_bold"])],
        [Paragraph("Bowling Team Win Probability", sty["table_cell_bold"]), Paragraph(f"{prediction_data['bowling_win_prob']:.2f}%", sty["table_cell_bold"])],
        [Paragraph("Prediction Confidence Level", sty["table_cell_bold"]), Paragraph(prediction_data["confidence_level"], sty["table_cell_bold"])],
        [Paragraph("Required Run Rate (RRR)", sty["table_cell"]), Paragraph(f"{prediction_data['rrr']:.2f} runs/over", sty["table_cell"])],
        [Paragraph("Current Run Rate (CRR)", sty["table_cell"]), Paragraph(f"{prediction_data['crr']:.2f} runs/over", sty["table_cell"])],
    ]
    t_pred = Table(pred_data, colWidths=[200, 320])
    t_pred.setStyle(TableStyle([
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor("#e5e7eb")),
        ('PADDING', (0,0), (-1,-1), 6),
        ('BACKGROUND', (0,0), (0,-1), colors.HexColor("#eff6ff")), # Subtle blue highlight
    ]))
    story.append(t_pred)
    
    doc.build(story)
    buffer.seek(0)
    return buffer.getvalue()
